# -*- coding: utf-8 -*-
"""Exercícios_Trello_M01S03_[Medium].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvwN2UaX6vSRNDUcfKHhivKjN1D0CvkL

Crie duas listas de compras: uma do João e outra da Maria. Use conjuntos para exibir:

Itens em comum;

Itens exclusivos de cada um;

Todos os itens sem duplicatas.
"""

lista_joao = ["Arroz", "Feijão", "Carne","Verduras","Cerveja"]
lista_maria = ["Arroz", "Feijão", "Carne", "Legumes", "Suco"]
lista_joao = set(lista_joao)
lista_maria = set(lista_maria)

print("Itens em comum: ")
items_comum = lista_joao & lista_maria
print(items_comum)
print()

exclusivos_joao = lista_joao - lista_maria
print(f"Itens exclusivos do João: {exclusivos_joao}")
exclusivos_maria = lista_maria - lista_joao
print(f"Itens exclusivos da Maria: {exclusivos_maria}")
print()

print("Todos os itens sem duplicatas: ")
todos_items = lista_joao.union(lista_maria)
print(todos_items)

"""Dado um dicionário com produtos e preços, exiba apenas os produtos com preço acima de R$ 100. Use items() e if.


"""

desktop_novo = {
    "mouse" : 70.00,
    "teclado" : 98.00,
    "monitor" : 980.00,
    "processador" : 1700.00,
    "headset" : 350.00,
    "gabinete" : 90.00
}
for chave, valor in desktop_novo.items():
  if valor > 100:
    print(f"O {chave} esta custando a bagatela de R$ {valor:.2f}")

"""Receba duas listas: uma com nomes e outra com idades. Converta para um dicionário onde cada nome é uma chave e a idade é o valor correspondente."""

lista_1 = []
lista_2 = []

for i in range(3):
  nomes = input(f"Digite o {i+1}º nome: ")
  lista_1.append(nomes)
print(lista_1)

for i in range(3):
  idades = int(input(f"Digite a {i+1}ª idade: "))
  lista_2.append(idades)
print(lista_2)

dicionario = dict(zip(lista_1, lista_2))
print(dicionario)