# -*- coding: utf-8 -*-
"""Filtro de Dicionário.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tXj35t7mKxrLNY9KJtrcCNDlWC_chYty

Dado um dicionário com produtos e preços, exiba apenas os produtos com preço acima de R$ 100. Use items() e if.
"""

desktop_novo = {
    "mouse" : 70.00,
    "teclado" : 98.00,
    "monitor" : 980.00,
    "processador" : 1700.00,
    "headset" : 350.00,
    "gabinete" : 90.00
}
for chave, valor in desktop_novo.items():
  if valor > 100:
    print(f"O {chave} esta custando a bagatela de R$ {valor:.2f}")