# -*- coding: utf-8 -*-
"""Trabalhando com Datas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LX5kg20W9OvdYEkRg6wpfx2agcgsF1DA

Desenvolva um programa que:

Leia uma data informada pelo usuário.

Calcule quantos dias faltam para o final do ano.

Mostre o dia da semana correspondente.

Entrega: Script .py funcionando corretamente com entrada e saída no terminal. Envie prints do terminal.
"""

from datetime import datetime, date

semana = ["Segunda-feira", "Terça-feira", "Quarta-feira","Quinta-feira", "Sexta-feira", "Sábado", "Domingo"]

data_entrada = input("Digite qualquer data no formato (DD/MM/AAA): ")

data = datetime.strptime(data_entrada, "%d/%m/%Y").date()

ult_dia = date(data.year, 12, 31)

falta_dias = (ult_dia - data).days

dia_semana = semana[data.weekday()]

print(f"Data de entrada: {data.strftime('%d/%m/%Y')}")
print(f"Dia da semana: {dia_semana} !")
print(f"Falta {falta_dias} dias para o final do ano !")